/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gringottsbank;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author vinicius
 */
public class TelaPrincipal extends javax.swing.JFrame {

    static Fila fila = new Fila();
    public TelaPrincipal() {
        initComponents();
        this.setResizable(false);
        setSize(1120,768);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        Date lbldata = new Date();
                            SimpleDateFormat formatadors = new SimpleDateFormat("dd/MM/yyyy");
                            jFormattedTextField1.setText(formatadors.format(lbldata));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bntGerarSenha = new javax.swing.JButton();
        Prioritario = new javax.swing.JCheckBox();
        Lux = new javax.swing.JCheckBox();
        Gold = new javax.swing.JCheckBox();
        Standart = new javax.swing.JCheckBox();
        Basic = new javax.swing.JCheckBox();
        LabelExibirSenha = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        TextoTipo = new javax.swing.JLabel();
        ChamarSenhas = new javax.swing.JButton();
        FundoFoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        bntGerarSenha.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        bntGerarSenha.setText("Gerar Senha");
        bntGerarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntGerarSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(bntGerarSenha);
        bntGerarSenha.setBounds(390, 570, 360, 140);

        buttonGroup1.add(Prioritario);
        Prioritario.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        Prioritario.setForeground(new java.awt.Color(255, 242, 0));
        Prioritario.setText("PRIORITARIO");
        getContentPane().add(Prioritario);
        Prioritario.setBounds(100, 370, 120, 30);

        buttonGroup1.add(Lux);
        Lux.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        Lux.setForeground(new java.awt.Color(253, 205, 18));
        Lux.setText("GB LUX");
        Lux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuxActionPerformed(evt);
            }
        });
        getContentPane().add(Lux);
        Lux.setBounds(100, 420, 110, 30);

        buttonGroup1.add(Gold);
        Gold.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        Gold.setForeground(new java.awt.Color(255, 217, 0));
        Gold.setText("GB GOLD");
        Gold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoldActionPerformed(evt);
            }
        });
        getContentPane().add(Gold);
        Gold.setBounds(100, 470, 90, 30);

        buttonGroup1.add(Standart);
        Standart.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        Standart.setForeground(new java.awt.Color(245, 204, 20));
        Standart.setText("GB STANDART");
        getContentPane().add(Standart);
        Standart.setBounds(100, 520, 120, 30);

        buttonGroup1.add(Basic);
        Basic.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        Basic.setForeground(new java.awt.Color(250, 230, 1));
        Basic.setText("GB BASIC");
        getContentPane().add(Basic);
        Basic.setBounds(100, 560, 110, 30);

        LabelExibirSenha.setFont(new java.awt.Font("Open Sans", 1, 48)); // NOI18N
        LabelExibirSenha.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(LabelExibirSenha);
        LabelExibirSenha.setBounds(480, 410, 200, 50);

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField1);
        jFormattedTextField1.setBounds(1010, 700, 100, 29);

        TextoTipo.setFont(new java.awt.Font("Open Sans", 1, 16)); // NOI18N
        TextoTipo.setForeground(new java.awt.Color(252, 255, 0));
        TextoTipo.setText("SELECIONE SEU TIPO DE CLIENTE:");
        getContentPane().add(TextoTipo);
        TextoTipo.setBounds(20, 340, 270, 23);

        ChamarSenhas.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        ChamarSenhas.setText("Chamar Senhas");
        getContentPane().add(ChamarSenhas);
        ChamarSenhas.setBounds(920, 420, 170, 32);

        FundoFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gringottsbank/TelaInicial.png"))); // NOI18N
        getContentPane().add(FundoFoto);
        FundoFoto.setBounds(0, 0, 1120, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntGerarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntGerarSenhaActionPerformed
        if(Basic.isSelected()!=true&&Gold.isSelected()!=true&&Lux.isSelected()!=true&&Prioritario.isSelected()!=true&&Standart.isSelected()!=true){
            JOptionPane.showMessageDialog(this,"SELECIONE UM TIPO DE CLIENTE!");
        }
        if(Prioritario.isSelected()){
            fila.adicionar("A00"+fila.A);
            LabelExibirSenha.setText("A00"+fila.A);
            fila.A++; 
        }else if(Lux.isSelected()){
            fila.adicionar("B00"+fila.B);
            LabelExibirSenha.setText("B00"+fila.B);
            fila.B++;
        }else if(Gold.isSelected()){
            fila.adicionar("C00"+fila.C);
            LabelExibirSenha.setText("C00"+fila.C);
            fila.C++;
        }else if(Standart.isSelected()){
            fila.adicionar("D00"+fila.D);
            LabelExibirSenha.setText("D00"+fila.D);
            fila.D++;
        }else if(Basic.isSelected()){
            fila.adicionar("E00"+fila.E);
            LabelExibirSenha.setText("E00"+fila.E);
            fila.E++;
        }
       
       //desmarcando tudo!
        buttonGroup1.clearSelection();
          
        
    }//GEN-LAST:event_bntGerarSenhaActionPerformed

    private void LuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LuxActionPerformed

    private void GoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GoldActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Basic;
    private javax.swing.JButton ChamarSenhas;
    private javax.swing.JLabel FundoFoto;
    private javax.swing.JCheckBox Gold;
    private javax.swing.JLabel LabelExibirSenha;
    private javax.swing.JCheckBox Lux;
    private javax.swing.JCheckBox Prioritario;
    private javax.swing.JCheckBox Standart;
    private javax.swing.JLabel TextoTipo;
    private javax.swing.JButton bntGerarSenha;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    // End of variables declaration//GEN-END:variables
}
